import React from 'react';
import '../../../app/globals.css';

export const metadata = {
   title: 'Next.js',
   description: 'Generated by Next.js',
};

export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="es">
         <body>
            <main className="bg-white">{children}</main>
         </body>
      </html>
   );
}
